### ISSUE TITLE
Typo: "Try agian later"

### ISSUE THREAD

**Issue by hugovk** [VerifiedJoseph/Save-to-the-Wayback-Machine#1]
![image](https://cloud.githubusercontent.com/assets/1324225/23250977/11aeed20-f9b4-11e6-9f13-27bafebc9150.png)

Should be "Try again later"

I would've made a PR but couldn't find the source file here, just tests. Are they missing?

**Comment by VerifiedJoseph** [comment]
Typo was fixed in version 4.4.0 (Released 17/03/17).
