### ISSUE TITLE
Archiving Broken

### ISSUE THREAD

**Issue by krackers** [VerifiedJoseph/Save-to-the-Wayback-Machine#125]
It seems that saving webpages by making a `GET` request to the endpoint `https://web.archive.org/save/[page url]` is no longer supported. The official Internet Archive extension does this by `POST`ing to `https://web.archive.org/save/` with the url as a body parameter. That unfortunately seems to require sending a valid account cookie along with the request (so only logged-in users can save webpages).

**Comment by VerifiedJoseph** [comment]
Thanks for reporting this.

The Internet Archive seems to have fixed the issue that stop the extension from the saving pages.
