### ISSUE TITLE
“Page has not been archived” even when pages are saved.

### ISSUE THREAD

**Issue by GhbSmwc** [VerifiedJoseph/Save-to-the-Wayback-Machine#155]
I've noticed that the extension is always saying “Page has not been archived” even when the pages have been saved already. For example: looking at “google.com”, the homepage was saved 5.3 billion times, but still say “Page has not been archived”. Not sure if the WBM changed the API on the naming of variables or a specific info that was needed was temporally down.

**Comment by VerifiedJoseph** [comment]
The Internet Archive's [Wayback Availability JSON API](https://archive.org/help/wayback_api.php) is somewhat temperamental, sometimes it fails to return snapshot details or returns details for an older snapshot. As this is an issue with the Wayback Machine, there is nothing I can do to fix it. Saving the page again normal fixes this issue.

**Comment by aaronraimist** [comment]
You don't have any contact info for the people who provide the API to tell them it is broken? Every single page says "Page has not been archived." for the past week or so.

**Comment by VerifiedJoseph** [comment]
I've sent an email to the Internet Archive about the issues with the API. I'll keep you posted.

**Comment by makeworld-the-better-one** [comment]
It appears to be completely working now. I would support this issue being closed.

**Comment by VerifiedJoseph** [comment]
It does seem to be fixed. l'm closing this issue for now, feel free to comment here if it breaks again.
