### ISSUE TITLE
Text invisible in both Options and Toolbar Button on Firefox

### ISSUE THREAD

**Issue by Atralb** [VerifiedJoseph/Save-to-the-Wayback-Machine#174]
Here are two screenshot explaining the issue better than words:

![2021-02-03-022533_2560x1440_scrot](https://user-images.githubusercontent.com/35039163/106684913-a5d48e00-65c7-11eb-8621-588936b2c7a0.png)

![2021-02-03-023030_1226x1296_scrot](https://user-images.githubusercontent.com/35039163/106684997-cc92c480-65c7-11eb-96db-d63e3ef11d7d.png)

I can see that the text is there by selecting it.

System:
- Firefox 85.0
- Extension just installed.

PS: This is not an issue with Darkreader. Even completely disabling it doesn't change the issue.

**Comment by VerifiedJoseph** [comment]
Are you still having this issue? What happens when you try and select the text (cotrl-A or system equivalent) that should be displayed?
