### ISSUE TITLE
Archive link/image from context menu

### ISSUE THREAD

**Issue by awendland** [VerifiedJoseph/Save-to-the-Wayback-Machine#88]
Huge thanks @VerifiedJoseph for creating this extension! It provides such a great user experience for interacting with Archive.org. I've happily had this installed for the past several months and use it on a weekly basis, it's a wonderful improvement over having to open a new tab to use the wayback machine directly.

**Request**

I was wondering hoping that you might be able to extend the functionality a little further and add support for **archiving links and images from the context menu**. This would make it much easier to archive things like PDF documents that have been linked from the page (or other downloadable material).

I imagine it would work similar to how the context menu entry works currently, just the HTML element under the cursor would be the target of what is saved.

**Implementation**

I looked through another extension and it looks like it should hopefully be straightforward to add the feature. Here's a line relating to how the other extension handles it https://github.com/jonathanmccann/archive-url-firefox-addon/blob/master/archive.js#L200. I'd be happy to add this myself if that would be best (though I thought it might be quicker for you to do it instead of us going back and forth on a PR and me getting the coding style wrong).

Thanks again for making this extension, it's been great to use (on both Chrome, Brave, and Firefox)!

**Comment by VerifiedJoseph** [comment]
@awendland That's a great idea. I've had a look at the [documentation](https://developer.chrome.com/apps/contextMenus) and code you linked, it does look pretty straightforward.
